# Generated by Django 5.0.1 on 2024-01-28 20:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Admin', '0003_tbl_admin'),
        ('Guest', '0004_alter_tbl_filmuploader_uploader_photo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_film',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('film_title', models.CharField(max_length=50)),
                ('film_disc', models.CharField(max_length=50)),
                ('film_duration', models.CharField(max_length=50)),
                ('film_poster', models.FileField(upload_to='uploaderdocs/')),
                ('upload_date', models.DateField(auto_now_add=True)),
                ('film_file', models.FileField(upload_to='uploaderdocs/')),
                ('film_genre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_genre')),
                ('film_lang', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.tbl_lang')),
                ('film_uploader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Guest.tbl_filmuploader')),
            ],
        ),
    ]
