# Generated by Django 4.2.7 on 2024-02-25 14:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Guest', '0004_alter_tbl_filmuploader_uploader_photo_and_more'),
        ('Admin', '0004_tbl_subscription'),
        ('Filmuploader', '0003_tbl_film_film_status_alter_tbl_film_film_file_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_chat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_content', models.CharField(max_length=500)),
                ('chat_time', models.DateTimeField()),
                ('chat_file', models.FileField(upload_to='ChatFiles/')),
                ('admin_from', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='admin_from', to='Admin.tbl_admin')),
                ('admin_to', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='doctor_to', to='Admin.tbl_admin')),
                ('uploader_from', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='uploader_from', to='Guest.tbl_filmuploader')),
                ('uploader_to', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='uploader_to', to='Guest.tbl_filmuploader')),
            ],
        ),
    ]
