# Generated by Django 5.0.1 on 2024-01-10 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_filmuploader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uploader_name', models.CharField(max_length=50)),
                ('uploader_email', models.CharField(max_length=50)),
                ('uploader_contact', models.CharField(max_length=50)),
                ('uploader_address', models.CharField(max_length=100)),
                ('uploader_photo', models.FileField(max_length=50, upload_to='')),
                ('uploader_proof', models.FileField(max_length=50, upload_to='')),
                ('uploader_password', models.CharField(max_length=50)),
                ('uploader_vstatus', models.CharField(max_length=2)),
            ],
        ),
    ]
