# Generated by Django 5.0.1 on 2024-01-14 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Guest', '0002_tbl_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_filmuploader',
            name='uploader_vstatus',
            field=models.CharField(default=0, max_length=2),
        ),
    ]
