# Generated by Django 5.0.1 on 2024-02-11 16:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Filmuploader', '0003_tbl_film_film_status_alter_tbl_film_film_file_and_more'),
        ('Guest', '0004_alter_tbl_filmuploader_uploader_photo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_wishlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wishlist_status', models.CharField(default=0, max_length=50)),
                ('film_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Filmuploader.tbl_film')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Guest.tbl_user')),
            ],
        ),
    ]
