# Generated by Django 4.2.7 on 2024-02-25 08:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Guest', '0004_alter_tbl_filmuploader_uploader_photo_and_more'),
        ('Filmuploader', '0003_tbl_film_film_status_alter_tbl_film_film_file_and_more'),
        ('User', '0005_tbl_subscribedplans_payment_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='tbl_watchedfilm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('watch_status', models.CharField(default=0, max_length=10)),
                ('watch_date', models.DateField(auto_now_add=True)),
                ('film', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Filmuploader.tbl_film')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Guest.tbl_user')),
            ],
        ),
    ]
