# Generated by Django 4.2.7 on 2024-02-25 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0006_tbl_watchedfilm'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tbl_watchedfilm',
            name='watch_date',
        ),
        migrations.AddField(
            model_name='tbl_watchedfilm',
            name='watch_datetime',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
