# Generated by Django 4.2.7 on 2024-02-25 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0007_remove_tbl_watchedfilm_watch_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_complaint',
            name='complaint_date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='tbl_feedback',
            name='feedback_date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
