# Generated by Django 4.2.7 on 2024-02-25 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0008_alter_tbl_complaint_complaint_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbl_complaint',
            name='complaint_reply',
            field=models.CharField(default='Not Replied', max_length=50),
        ),
        migrations.AlterField(
            model_name='tbl_complaint',
            name='complaint_status',
            field=models.CharField(default=0, max_length=50),
        ),
    ]
